# Generated by Django 5.1.15 on 2026-01-18 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_event_flipbook_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipBookAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('flipbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='books.flipbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flipbook_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FlipBook Access',
                'verbose_name_plural': 'FlipBook Accesses',
                'unique_together': {('user', 'flipbook')},
            },
        ),
    ]
