# Generated by Django 6.1.dev20260123123123 on 2026-01-27 13:54

from django.db import migrations, models
from django.utils import timezone
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_unlockrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlockrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='unlockrequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='unlockrequest',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='unlockrequest',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='unlockrequest',
            name='purpose',
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='candidate_full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], default='single', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='parents_mobile_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='payment_screenshot',
            field=models.ImageField(default='', upload_to='payment_screenshots/'),
            preserve_default=False,
        ),
    ]
