# Generated by Django 4.2.18 on 2026-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_unlockrequest_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlockrequest',
            name='payment_screenshot',
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#2E86AB', help_text='Hex color code', max_length=7),
        ),
    ]
