# Generated by Django 4.2.18 on 2026-03-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_userloginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockrequest',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
