# Generated by Django 4.2.18 on 2026-03-06 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_unlockrequest_payment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockRequestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('flipbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.flipbook')),
                ('unlock_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_books_list', to='books.unlockrequest')),
            ],
            options={
                'verbose_name': 'Unlock Request Book',
                'verbose_name_plural': 'Unlock Request Books',
                'unique_together': {('unlock_request', 'flipbook')},
            },
        ),
    ]
