# Generated by Django 4.2.30 on 2026-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipbook',
            name='boys_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='યુવકો (Boys)'),
        ),
        migrations.AddField(
            model_name='flipbook',
            name='girls_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='યુવતીઓ (Girls)'),
        ),
        migrations.AddField(
            model_name='flipbook',
            name='total_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
