# Generated by Django 4.2.30 on 2026-08-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_flipbook_boys_count_flipbook_girls_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flipbook',
            name='total_count',
        ),
    ]
